version: "2"
services:
  db_shortcut:
    image: postgres
    container_name: db_shortcut
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortcut
      - PGDATA=/var/lib/postgresql/data
    restart: always
  app_shortcut:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_shortcut:5432/shortcut
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db_shortcut