version: "2"
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortcut
      - PGDATA=/var/lib/postgresql/data
    restart: always
  app:
    image: shortcut
    container_name: shortcut
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shortcut
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - db